### ISSUE TITLE
Set up CI server to run specs after they are written

### ISSUE THREAD

**Issue by ajwann** [ajwann/svg-loaders-react#13]

**Comment by pandasa123** [comment]
Finished off writing travis yml. All that needs to be done now is just integrate it for the repo

https://github.com/ajwann/svg-loaders-react/pull/18

**Comment by ajwann** [comment]
Awesome! I see on you PR that you are planning on writing specs and also adding linting. Were you going to add those to #18 or did you want to put up a separate PR?

**Comment by ajwann** [comment]
I'm going to go ahead and merge #18 so I can sync Travis.

**Comment by pandasa123** [comment]
I added the linting now! Realistically, what are you looking for in terms of specs?

**Comment by pandasa123** [comment]
Also, separate note: why JavaScript instead of TypeScript?

**Comment by ajwann** [comment]
@pandasa123 I prefer plain ES6+ instead of Typescript. All official React doc examples are written in ES6+ as well, which matters a lot to me.
