### ISSUE TITLE
Feature request: add default classNames to globally handle customizations

### ISSUE THREAD

**Issue by YuriScarbaci** [ajwann/svg-loaders-react#30]
It would be pretty sweet if all the components would come with a default className, this would allow us to handle svg customization from css on a global level instead of having to repeat the className everytime the spinner is used or the fill...

**Comment by ajwann** [comment]
Hi @YuriScarbaci, I like this idea. All that needs to be done to make it work is for a prop to be added to each components root element named ```className```, right after the ```heighth``` and ```width``` props.

**Comment by YuriScarbaci** [comment]
Hello @ajwann 

first time creating a PR for a github repo, I hope I didn't screw things up.

This is the PR for the feature https://github.com/ajwann/svg-loaders-react/pull/32

I went for `svg-loaders-svg` instead of `svg-loaders-default` because I found it more explanatory about what element it's appended to.

also your version
`<svg width={55} height={80} fill="#FFF" className="svg-loaders-default" {...props}>`
would not allow the default class to be kept in case someone wanted to customize their classNames and also keeping the default one, yours would overwrite the default one which defeats the purpose of globally handling by css...

I went for 
`className={`svg-loaders-svg${className?` ${className}`:''}`}` wich would append user defined classNames after the default one (allowing for better BEM css naming)

**Comment by ajwann** [comment]
@YuriScarbaci nice, I like your solution. Thanks for the PR!
