### ISSUE TITLE
It isn't clear how to change the size of the svg with this library

### ISSUE THREAD

**Issue by adamthedeveloper** [ajwann/svg-loaders-react#31]
Hello,

Thanks for creating this library!

I've tried all sorts of ways to re-size the svg, fontSize, width, height. Nothing seems to work. When I go here: https://samherbert.net/svg-loaders/ 

I can change the width directly on the "rings" svg and it just works. I'm trying to understand what this react layer is doing and why the size can't be controlled as easily. Any suggestions?

Thanks

**Comment by ajwann** [comment]
Hi @adamthedeveloper, to resize any of the loading indicators you should just have to change the ```heigth``` and ```width``` props.

Here is an example of how you would do that when rendering a loading indicator:
```<Audio heigth={100} width={100} />```

Please let me know if the above method works for you. 
This may be a good chance to update the readme.

**Comment by YuriScarbaci** [comment]
The Svg aren't defining a viewPort, as such when applying a width/height that is lower than the content of every single svg, the svg doesn't scale and are being render in strange ways.

for example the following render would be totally broken:
`<Oval height={15} width={15} className="svg-loaders-svg" />`

whereas the following
```
             <Oval 
                  className="svg-loaders-svg" 
                  viewBox="0 0 38 38"
                  height={15} 
                  width={15}
              />
```

would scale the svg as one would expect it to be scaled...

I think we should integrate the `viewBox` in all the svg by default, to make this whole process easier...

@ajwann  any toughts?

**Comment by ajwann** [comment]
@adamthedeveloper this sounds like a great idea. Do you want to put up a pull request with some jest specs?

Some specs that test that each component has the expected ```viewBox``` value would suffice.

**Comment by YuriScarbaci** [comment]
> @adamthedeveloper this sounds like a great idea. Do you want to put up a pull request?
> 
> Some specs that test that each component has the expected `viewBox` value would also be nice.

Did you mean to tag me?

I have a busy schedule lately and I don't have the time right now to get the correct viewbox for every svg...

**Comment by ajwann** [comment]
Sorry @YuriScarbaci , I did mean to tag you. I'll give this item an appropriate label so someone can pick it up eventually.

**Comment by ajwann** [comment]
For anyone that wants to pick this up, we want to define a sensible ```viewBox``` value for each svg. Here are the docs for how the [viewBox](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox) attribute behaves. 

Maybe we can get away with settings standard viewbox value for each svg, maybe we have to plug and play for a bit to determine sensible viewBox values for each svg.
