### ISSUE TITLE
Latest version of the package not published in npm packages

### ISSUE THREAD

**Issue by YuriScarbaci** [ajwann/svg-loaders-react#33]
https://www.npmjs.com/package/svg-loaders-react states latest publish was 2 months ago,

Latest PR ( which includes default classNames PR) was 4 days ago.

`npm install` results in a version without default classNames,  `npm update` fails to detect a new minor release.

is this due to a missing bump of the package version in the package.json ?

should the test stage check for a change in the package.json version to ensure this won't happen again?

**Comment by ajwann** [comment]
Sorry about that, I wanted to get a security fix merged before doing a release.
This repo is already set up to deploy via CI when a new git tag is detected, and I'll make that tag now.
